import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "TranspTimer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="bg-zinc-950 transition-all ease-in-out duration-500">
        {children}
      </body>
    </html>
  );
}
